// Command midi2go converts midi into an array of engine notes.
// This exists because it avoids me having to process midis directly on an embedded device freeing up rom and runtime.
//
//	 Usage:
//
//		//go:generate go run ./midi2go -in assets/midi -out assets/music
//
// then run `go generate ./...`.
package main

import (
	"errors"
	"flag"
	"fmt"
	"html/template"
	"os"
	"path/filepath"
	"strings"
	"unicode"

	"gitlab.com/gomidi/midi/v2"
	"gitlab.com/gomidi/midi/v2/smf"
)

func main() {
	in := flag.String("in", ".", "directory of source midi files")
	out := flag.String("out", ".", "directory to write .go music files")
	flag.Parse()

	if err := run(*in, *out); err != nil {
		fmt.Fprintf(os.Stderr, "midi2go: %e", err)
		os.Exit(1)
	}
}

func run(inDir, outDir string) error {
	entries, err := os.ReadDir(inDir)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}

	count := 0
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		if !strings.EqualFold(filepath.Ext(e.Name()), ".mid") {
			fmt.Fprintf(os.Stdout, "skipping: %s", e.Name())
			continue
		}
		src := filepath.Join(inDir, e.Name())
		name := strings.TrimSuffix(e.Name(), filepath.Ext(e.Name())) + ".go"
		dst := filepath.Join(outDir, name)
		if err := convert(src, dst); err != nil {
			return fmt.Errorf("%s: %w", e.Name(), err)
		}
		fmt.Printf("png2p5: %s -> %s\n", src, dst)
		count++
	}

	fmt.Printf("midi2go: converted %d file(s)\n", count)
	return nil
}

type Entry struct {
	Key uint8
	Dur uint
}

func gcd(a, b uint) uint {
	for b != 0 {
		a, b = b, a%b
	}
	return a
}

func convert(src, dst string) error {
	f, err := os.Open(src)
	if err != nil {
		return err
	}
	defer f.Close()

	divisor := uint(0) // Greatest common divisor in milliseconds
	notes := []Entry{}
	current := uint8(0)
	startUs := int64(0)
	var midiErr error = nil

	err = smf.ReadTracksFrom(f).
		Do(
			func(te smf.TrackEvent) {
				if midiErr != nil {
					return
				}
				if !te.Message.IsMeta() {
					var ch, key, velocity uint8
					if te.Message.Type().Is(midi.NoteOnMsg) {
						te.Message.GetNoteOn(&ch, &key, &velocity)
						if ch != 0 {
							return // Not interested in other channels.
						}
						if current != 0 {
							midiErr = errors.New("Parse error, may only play one note at a time.")
							return
						}
						current = key
						startUs = te.AbsMicroSeconds
					}
					if te.Message.Type().Is(midi.NoteOffMsg) {
						te.Message.GetNoteOff(&ch, &key, &velocity)
						if ch != 0 {
							return // Not interested in other channels.
						}
						if current != key {
							midiErr = errors.New("Parse error, stopped note is not currently playing")
							return
						}
						current = 0
						dur := uint((te.AbsMicroSeconds - startUs) / 1000)

						if divisor == 0 {
							divisor = dur
						} else {
							divisor = gcd(dur, divisor) // Keep finding the greatest common divisor.
						}

						notes = append(notes, Entry{Key: key, Dur: dur})
						// fmt.Printf("@%dms NoteOff: %d\n", te.AbsMicroSeconds/1000, key)
					}

				}
			},
		).Error()
	if err != nil {
		return err
	}
	if midiErr != nil {
		return midiErr
	}

	for i := range notes {
		notes[i].Dur = notes[i].Dur / divisor
	}

	return writeGo(dst, divisor, notes)
}

func writeGo(path string, msPerDur uint, notes []Entry) error {

	type templateData struct {
		Package  string
		Name     string
		MsPerDur uint
		Notes    []Entry
	}

	data := templateData{
		Package:  filepath.Base(filepath.Dir(path)),
		Name:     toCamel(filepath.Base(path)),
		MsPerDur: msPerDur,
		Notes:    notes,
	}

	var tmpl = template.Must(template.New("imgs").Parse(`// Generated by midi2go;
package {{.Package}}

import (
	"github.com/hoani/3310_engine/engine/sound"
	"github.com/hoani/3310_engine/engine/sound/note"
)

var {{.Name}} = sound.Sound({{.MsPerDur}}, {{range .Notes}}
	sound.Note(note.IndexFromMidi({{.Key}}), 0xFF, {{.Dur}}),{{end}}
)
`))

	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	if err := tmpl.Execute(f, data); err != nil {
		_ = f.Close()
		return fmt.Errorf("executing template for %s: %w", data.Name, err)
	}
	if err := f.Close(); err != nil {
		return fmt.Errorf("closing file for %s: %w", data.Name, err)
	}

	return nil
}

func toCamel(filename string) string {
	base := strings.TrimSuffix(filename, filepath.Ext(filename))
	fields := strings.FieldsFunc(base, func(r rune) bool {
		return !unicode.IsLetter(r) && !unicode.IsDigit(r)
	})
	var b strings.Builder
	for _, f := range fields {
		r := []rune(f)
		b.WriteRune(unicode.ToUpper(r[0]))
		b.WriteString(string(r[1:]))
	}
	name := b.String()
	if name == "" {
		return "Snd"
	}
	if unicode.IsDigit([]rune(name)[0]) { // identifiers can't start with a digit
		name = "Snd" + name
	}
	return name
}
