// Generated by midi2go;
package music

import (
	"github.com/hoani/3310_engine/engine/sound"
	"github.com/hoani/3310_engine/engine/sound/note"
)

var Song = sound.Sound(400, 
	sound.Note(note.IndexFromMidi(64), 0xFF, 1),
	sound.Note(note.IndexFromMidi(67), 0xFF, 1),
	sound.Note(note.IndexFromMidi(64), 0xFF, 1),
	sound.Note(note.IndexFromMidi(67), 0xFF, 1),
	sound.Note(note.IndexFromMidi(69), 0xFF, 2),
	sound.Note(note.IndexFromMidi(64), 0xFF, 1),
	sound.Note(note.IndexFromMidi(67), 0xFF, 1),
	sound.Note(note.IndexFromMidi(64), 0xFF, 1),
	sound.Note(note.IndexFromMidi(67), 0xFF, 1),
	sound.Note(note.IndexFromMidi(69), 0xFF, 2),
	sound.Note(note.IndexFromMidi(64), 0xFF, 1),
	sound.Note(note.IndexFromMidi(67), 0xFF, 1),
	sound.Note(note.IndexFromMidi(64), 0xFF, 1),
	sound.Note(note.IndexFromMidi(67), 0xFF, 1),
	sound.Note(note.IndexFromMidi(69), 0xFF, 2),
	sound.Note(note.IndexFromMidi(64), 0xFF, 1),
	sound.Note(note.IndexFromMidi(67), 0xFF, 1),
	sound.Note(note.IndexFromMidi(64), 0xFF, 1),
	sound.Note(note.IndexFromMidi(67), 0xFF, 1),
	sound.Note(note.IndexFromMidi(69), 0xFF, 2),
)
