// Command img2p5 converts PNG sprites into 8-bit binary
// PGM (P5) files. Three states are encoded in the gray value so a single
// file stays fully previewable in tools which support p5.
//
//	  0 = ink        (opaque + dark  -> black on the display)
//	255 = paper      (opaque + light -> white on the display)
//	128 = transparent(alpha 0        -> mask off; skip when blitting)
//
// Because the display treats 1 as black and PGM treats 0 as black, ink maps
// to 0 here and previews match the screen with no inversion.
//
// Wire it up next to the package that will embed the sprites:
//
//	//go:generate go run ./png2p5 -in assets/png -out assets/pgm
//
// then run `go generate ./...`.
package main

import (
	"bufio"
	"flag"
	"fmt"
	"html/template"
	"image/png"
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

const (
	valInk         = 0    // opaque + dark
	valPaper       = 0xf9 // opaque + light
	valTransparent = 0xff // alpha below the cut
)

func main() {
	in := flag.String("in", ".", "directory of source PNG files")
	out := flag.String("out", ".", "directory to write .pgm (P5) files")
	threshold := flag.Int("threshold", 128, "luminance 0-255 below which an opaque pixel is ink")
	alphaCut := flag.Int("alpha", 128, "alpha 0-255 at or above which a pixel is opaque")
	gray := flag.Bool("gray", false, "retain grayscale values (default: two-colour threshold)")
	flag.Parse()

	if err := run(*in, *out, *gray, *threshold, *alphaCut); err != nil {
		fmt.Fprintf(os.Stderr, "img2p5: %e", err)
		os.Exit(1)
	}
}

func run(inDir, outDir string, gray bool, threshold, alphaCut int) error {
	entries, err := os.ReadDir(inDir)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}

	count := 0
	imgs := []string{}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		if !strings.EqualFold(filepath.Ext(e.Name()), ".png") {
			fmt.Fprintf(os.Stdout, "skipping: %s", e.Name())
			continue
		}
		src := filepath.Join(inDir, e.Name())
		imgName := strings.TrimSuffix(e.Name(), filepath.Ext(e.Name())) + ".pgm"
		imgs = append(imgs, imgName)
		dst := filepath.Join(outDir, imgName)
		if err := convert(src, dst, gray, threshold, alphaCut); err != nil {
			return fmt.Errorf("%s: %w", e.Name(), err)
		}
		fmt.Printf("png2p5: %s -> %s\n", src, dst)
		count++
	}

	embName := filepath.Base(outDir)
	if gray {
		embName += "_gray"
	}
	embName += ".go"
	writeEmbeds(outDir, embName, imgs)

	fmt.Printf("png2p5: converted %d file(s)\n", count)
	return nil
}

func encodeShade(gray int) byte {
	level := (gray*32 + 127) / 255 // round(gray/255 * 32) -> 0..32
	if level >= 32 {
		return valPaper
	}
	return byte(level << 3)
}

func convert(src, dst string, gray bool, threshold, alphaCut int) error {
	f, err := os.Open(src)
	if err != nil {
		return err
	}
	defer f.Close()

	img, err := png.Decode(f)
	if err != nil {
		return err
	}
	b := img.Bounds()
	w, h := b.Dx(), b.Dy()

	pix := make([]byte, 0, w*h)
	for y := b.Min.Y; y < b.Max.Y; y++ {
		for x := b.Min.X; x < b.Max.X; x++ {
			r, g, bl, a := img.At(x, y).RGBA()

			if int(a>>8) < alphaCut {
				pix = append(pix, valTransparent)
				continue
			}

			// Perceived brighness
			lum := (299*int(r>>8) + 587*int(g>>8) + 114*int(bl>>8)) / 1000

			if gray {
				pix = append(pix, encodeShade(lum))
				continue
			}

			if lum < threshold {
				pix = append(pix, valInk)
			} else {
				pix = append(pix, valPaper)
			}

		}
	}

	return writeP5(dst, w, h, pix)
}

func writeP5(path string, w, h int, pix []byte) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	bw := bufio.NewWriter(f)
	// P5 header: magic \n width space height \n maxval \n, then raw raster,
	// one byte per pixel, top-to-bottom, left-to-right, no row padding.
	fmt.Fprintf(bw, "P5\n%d %d\n255\n", w, h)
	bw.Write(pix)
	return bw.Flush()
}

func writeEmbeds(path, name string, images []string) error {
	type Entry struct {
		VarName  string
		FileName string
	}

	type templateData struct {
		Package string
		Images  []Entry
	}

	data := templateData{
		Package: filepath.Base(path),
		Images:  make([]Entry, len(images)),
	}

	for i, img := range images {
		data.Images[i].FileName = img
		data.Images[i].VarName = toCamel(img)
	}

	var tmpl = template.Must(template.New("imgs").Parse(`// Generated by img2p5;
package {{.Package}}

import (
	_ "embed"
)
{{range .Images}}
//go:embed "{{.FileName}}"
var {{.VarName}} string
{{end}}
`))

	tmplPath := filepath.Join(path, name)
	f, err := os.Create(tmplPath)
	if err != nil {
		return err
	}
	defer f.Close()

	if err := tmpl.Execute(f, data); err != nil {
		_ = f.Close()
		return fmt.Errorf("executing template for %s: %w", name, err)
	}
	if err := f.Close(); err != nil {
		return fmt.Errorf("closing file for %s: %w", name, err)
	}

	return nil
}

func toCamel(filename string) string {
	base := strings.TrimSuffix(filename, filepath.Ext(filename))
	fields := strings.FieldsFunc(base, func(r rune) bool {
		return !unicode.IsLetter(r) && !unicode.IsDigit(r)
	})
	var b strings.Builder
	for _, f := range fields {
		r := []rune(f)
		b.WriteRune(unicode.ToUpper(r[0]))
		b.WriteString(string(r[1:]))
	}
	name := b.String()
	if name == "" {
		return "Img"
	}
	if unicode.IsDigit([]rune(name)[0]) { // identifiers can't start with a digit
		name = "Img" + name
	}
	return name
}
